<!doctype html>
<html>
	<head>
		<title>ProjectApp</title>
		<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="tree.css">
		<script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
	        <div class="container-fluid">
	            <div class="navbar-header">
	                <a class="navbar-brand" href="/treeproj/public">Lista kategorii</a>
	                <form class="navbar-form navbar-right" role="search">
					    <a href="add.php" class="btn btn-default">
					        <span class="glyphicon glyphicon-plus-sign"></span>
					        Nowa kategoria główna
					    </a>
					</form>
	            </div>
	        </div>
    	</nav>
    	<div class="container-fluid">
			<!-- Specific Page Content Goes Here -->
             <?php $this->content(); ?>
		</div>

	</body>
</html>