<?php
$config = \Tree\Config::get('site');
?>
<!doctype html>
<html>
	<head>
		<title><?=$config['title'];?></title>
		<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="tree.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
	        <div class="container-fluid">
	            <div class="navbar-header">
	                <a class="navbar-brand" href="/ideotree/public"><?=$config['title'];?></a>
	            </div>
	        </div>
    	</nav>
    	<div class="container-fluid">
			<!-- Specific Page Content Goes Here -->
             <?php $this->content(); ?>
		</div>

        <script>
            $('#checkall').click(function(){
                var d = $(this).data(); // access the data object of the button
                $(':checkbox').prop('checked', !d.checked); // set all checkboxes 'checked' property using '.prop()'
                d.checked = !d.checked; // set the new 'checked' opposite value to the button's data object
            });
        </script>
	</body>
</html>