<h2> Nowa kategoria </h2>
<form action="add.php" method="POST">
	<label>
		Nazwa : <input type="text" name="label">
	</label>
	<br>
	<input type="hidden" name="parent" value="0">
	<br>
	<label>
		Odnośnik: <input type="text" name="link">
	</label>
	<br>
	<br>
	<input type="submit" value="Dodaj węzeł" class="btn btn-primary">
	<a href="/treeproj/public" role="button" class="btn btn-warning">Powrót</a>
</form>