<?php
    $labels = $this->labels;
?>
<h2> Nowa kategoria </h2>
<form action="add.php" method="POST">
	<label>
		Nazwa : <input type="text" name="label">
	</label>
	<br>
    <label>
        Rodzic:
        <select name="parent">
            <option value="0">Kategoria główna</option>
            <?php
            foreach($labels as $label) {
                echo "<option value='".$label['id']."'>".$label['label']."</option>";
            }
            ?>
        </select>
    </label>
	<br>
	<br>
	<input type="submit" value="Dodaj węzeł" class="btn btn-primary">
	<a href="/treeproj/public" role="button" class="btn btn-warning">Powrót</a>
</form>