<?php
$nodeId = $this->nodeId;
$tree = $this->tree;
$node = $this->node;
?>


<div class="container">
    <h3 class="page-header">
        Kategoria : <?=$node['label'];?>
    </h3>

    <div class="row">
        <div class="col-md-6">
        <?php
            if (empty($tree)) {
                echo $node['label']." nie posiada jeszcze żadnych podkategorii.";
                echo "Możesz dodać podkategorię "."<a href='/ideotree/public/add.php'>TUTAJ</a>";
            } else {
                echo "Podkategorie :" . "<br>";
                echo $tree;
            }
        ?>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <button type="button" id="checkall" class="btn btn-xs btn-default">Zwiń/rozwiń drzewo</button>
                    <a href="edit.php?id=<?=$nodeId;?>" role="button" class="btn btn-xs btn-primary" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Edycja" data-content="Zmiana nazwy i przenoszenie węzła">Edytuj</a>
                    <a href="delete.php?id=<?=$nodeId;?>" role="button" class="btn btn-xs btn-danger" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Na pewno?" data-content="Ta operacja jest nieodwracalna!">Usuń</a>
                </div>
            </div>
        </div>
    </div>
</div>

