<?php
$node = $this->node;
$labels = $this->labels;
?>

<h2> Edit node </h2>
<form action="edit.php" method="POST">
	<label>
		Title: <input type="text" name="label" value="<?=$node['label'];?>">
	</label>
	<br>
	<label>
		Rodzic:
        <select name="parent">
            <?php
                foreach($labels as $label) {
                   echo "<option value='".$label['id']."'>".$label['label']."</option>";
                }
            ?>
            <option value="0">Kategoria główna</option>
        </select>
	</label>
	<br>
	<input type="hidden" name="id" value="<?=$node['id'];?>">
	<input type="submit" value="Edytuj węzeł" class="btn btn-primary">
	<a href="/ideotree/public" role="button" class="btn btn-warning">Powrót</a>
</form>
