<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->tree;
        ?>
    </div>

    <div class="col-md-6">
        <div class="well">
            <span class="glyphicon glyphicon-chevron-right"></span> - kliknij, aby zobaczyć szczegóły węzła<br>
            <span class="glyphicon glyphicon-chevron-down"></span> - kliknij, aby rozwinąć kategorię
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <button type="button" id="checkall" class="btn btn-default">Zwiń/rozwiń drzewo</button>
                <a href="add.php" class="btn btn-default">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    Nowa kategoria
                </a>
            </div>
        </div>
    </div>
</div>
