<div class="row">
    <div class="col-md-6">
        <?php
            echo $this->tree;
        ?>
    </div>

    <div class="col-md-6">
        <div class="well">
            <span class="glyphicon glyphicon-chevron-right"></span> - kliknij, aby zobaczyć szczegóły węzła<br>
            <span class="glyphicon glyphicon-chevron-down"></span> - kliknij, aby rozwinąć kategorię
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <button type="button" id="checkall" class="btn btn-default">Zwiń/rozwiń drzewo</button>
                <a href="add.php" class="btn btn-default">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    Nowa kategoria
                </a>
                <a href="tree.php?param=label&sort=ASC" class="btn btn-default" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Sortuj" data-content="A-Z">
                    <span class="glyphicon glyphicon-sort-by-alphabet"></span>
                </a>

                <a href="tree.php?param=label&sort=DESC" class="btn btn-default" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Sortuj" data-content="Z-A">
                    <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>
                </a>

                <a href="tree.php?param=id&sort=ASC" class="btn btn-default" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Sortuj" data-content="Od najwcześniej dodanych">
                    <span class="glyphicon glyphicon-sort-by-attributes"></span>
                </a>

                <a href="tree.php?param=id&sort=DESC" class="btn btn-default" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Sortuj" data-content="Od ostatnio dodanych">
                    <span class="glyphicon glyphicon-sort-by-attributes-alt"></span>
                </a>
            </div>
        </div>
    </div>
</div>
